# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_records', [dirname(__file__)])
        except ImportError:
            import _records
            return _records
        if fp is not None:
            try:
                _mod = imp.load_module('_records', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _records = swig_import_helper()
    del swig_import_helper
else:
    import _records
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Records(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Records, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Records, name)
    __repr__ = _swig_repr

    def __init__(self, filename, mode, delim=None, dtype=None, nrows=-9999, offset=0, bracket_arrays=0, padnull=False, ignorenull=False):
        this = _records.new_Records(filename, mode, delim, dtype, nrows, offset, bracket_arrays, padnull, ignorenull)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _records.delete_Records
    __del__ = lambda self: None

    def close(self):
        return _records.Records_close(self)

    def Write(self, obj):
        return _records.Records_Write(self, obj)

    def write_header_and_update_offset(self, obj):
        return _records.Records_write_header_and_update_offset(self, obj)

    def update_row_count(self, nrows):
        return _records.Records_update_row_count(self, nrows)

    def read_sfile_header(self):
        return _records.Records_read_sfile_header(self)

    def read_columns(self, arrayobj, colnums, rows):
        return _records.Records_read_columns(self, arrayobj, colnums, rows)

    def read_binary_slice(self, arrayobj, row1, row2, step):
        return _records.Records_read_binary_slice(self, arrayobj, row1, row2, step)
Records_swigregister = _records.Records_swigregister
Records_swigregister(Records)

# This file is compatible with both classic and new-style classes.


