# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_htmc', [dirname(__file__)])
        except ImportError:
            import _htmc
            return _htmc
        if fp is not None:
            try:
                _mod = imp.load_module('_htmc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _htmc = swig_import_helper()
    del swig_import_helper
else:
    import _htmc
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class HTMC(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HTMC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HTMC, name)
    __repr__ = _swig_repr

    def __init__(self, depth=10):
        this = _htmc.new_HTMC(depth)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def init(self, depth=10):
        return _htmc.HTMC_init(self, depth)
    __swig_destroy__ = _htmc.delete_HTMC
    __del__ = lambda self: None

    def lookup_id(self, ra_array, dec_array):
        """

        Class:
            HTM

        Method Name:
            lookup_id

        Purpose:

            Return the index of the input ra/dec at the current htm depth.   ra/dec may
            be arrays.

        Calling Sequence:

            import esutil
            h=esutil.htm.HTM(depth)
            htmid = h.lookup_id(ra, dec)

        Inputs:
            ra,dec:  Scalars or arrays of equal length.

        Outputs:
            htmid:  An array with the htm id.

        Example:

            >>> import esutil
            >>> h=esutil.htm.HTM(depth)
            >>> htmid = h.lookup_id(ra, dec)

        Revision History:
            2010-03-03:  SWIG wrapper completed.  Erin Sheldon, BNL.

        """
        return _htmc.HTMC_lookup_id(self, ra_array, dec_array)


    def intersect(self, ra, dec, radius, inclusive):
        """

        Class:
            HTM

        Method Name:
            lookup_id

        Purpose:

            Return the index of the input ra/dec at the current htm depth.   ra/dec may
            be arrays.

        Calling Sequence:

            import esutil
            h=esutil.htm.HTM(depth)
            htmid = h.lookup_id(ra, dec)

        Inputs:
            ra,dec:  Scalars or arrays of equal length.

        Outputs:
            htmid:  An array with the htm id.

        Example:

            >>> import esutil
            >>> h=esutil.htm.HTM(depth)
            >>> htmid = h.lookup_id(ra, dec)

        Revision History:
            2010-03-03:  SWIG wrapper completed.  Erin Sheldon, BNL.

        """
        return _htmc.HTMC_intersect(self, ra, dec, radius, inclusive)


    def cmatch(self, radius_array, ra1_array, dec1_array, ra2_array, dec2_array, htmrev2_array, minid_obj, maxid_obj, maxmatch_obj, filename):
        """

        Class:
            HTM

        Method Name:
            lookup_id

        Purpose:

            Return the index of the input ra/dec at the current htm depth.   ra/dec may
            be arrays.

        Calling Sequence:

            import esutil
            h=esutil.htm.HTM(depth)
            htmid = h.lookup_id(ra, dec)

        Inputs:
            ra,dec:  Scalars or arrays of equal length.

        Outputs:
            htmid:  An array with the htm id.

        Example:

            >>> import esutil
            >>> h=esutil.htm.HTM(depth)
            >>> htmid = h.lookup_id(ra, dec)

        Revision History:
            2010-03-03:  SWIG wrapper completed.  Erin Sheldon, BNL.

        """
        return _htmc.HTMC_cmatch(self, radius_array, ra1_array, dec1_array, ra2_array, dec2_array, htmrev2_array, minid_obj, maxid_obj, maxmatch_obj, filename)


    def cbincount(self, rmin_object, rmax_object, nbin_object, ra1_array, dec1_array, ra2_array, dec2_array, htmrev2_array, minid_obj, maxid_obj, scale_object=None, verbose=0):
        """

        Class:
            HTM

        Method Name:
            lookup_id

        Purpose:

            Return the index of the input ra/dec at the current htm depth.   ra/dec may
            be arrays.

        Calling Sequence:

            import esutil
            h=esutil.htm.HTM(depth)
            htmid = h.lookup_id(ra, dec)

        Inputs:
            ra,dec:  Scalars or arrays of equal length.

        Outputs:
            htmid:  An array with the htm id.

        Example:

            >>> import esutil
            >>> h=esutil.htm.HTM(depth)
            >>> htmid = h.lookup_id(ra, dec)

        Revision History:
            2010-03-03:  SWIG wrapper completed.  Erin Sheldon, BNL.

        """
        return _htmc.HTMC_cbincount(self, rmin_object, rmax_object, nbin_object, ra1_array, dec1_array, ra2_array, dec2_array, htmrev2_array, minid_obj, maxid_obj, scale_object, verbose)


    def depth(self):
        """

        Class:
            HTM

        Method Name:
            lookup_id

        Purpose:

            Return the index of the input ra/dec at the current htm depth.   ra/dec may
            be arrays.

        Calling Sequence:

            import esutil
            h=esutil.htm.HTM(depth)
            htmid = h.lookup_id(ra, dec)

        Inputs:
            ra,dec:  Scalars or arrays of equal length.

        Outputs:
            htmid:  An array with the htm id.

        Example:

            >>> import esutil
            >>> h=esutil.htm.HTM(depth)
            >>> htmid = h.lookup_id(ra, dec)

        Revision History:
            2010-03-03:  SWIG wrapper completed.  Erin Sheldon, BNL.

        """
        return _htmc.HTMC_depth(self)

HTMC_swigregister = _htmc.HTMC_swigregister
HTMC_swigregister(HTMC)

class Matcher(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Matcher, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Matcher, name)
    __repr__ = _swig_repr

    def __init__(self, depth, ra, dec):
        this = _htmc.new_Matcher(depth, ra, dec)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _htmc.delete_Matcher
    __del__ = lambda self: None

    def get_depth(self):
        return _htmc.Matcher_get_depth(self)

    def match(self, radius_array, ra_array, dec_array, maxmatch_obj, filename):
        return _htmc.Matcher_match(self, radius_array, ra_array, dec_array, maxmatch_obj, filename)
Matcher_swigregister = _htmc.Matcher_swigregister
Matcher_swigregister(Matcher)

# This file is compatible with both classic and new-style classes.


